#!/bin/bash

# colors
red='\033[1;31m' yellow='\033[1;33m' blue='\033[1;34m' reset='\033[0m'

#Variable
ARCH=`uname -m` 
echo -e "$blue John The Ripper For Termux" 
echo 
echo -e " Checking Your Architecture" 
sleep 1 
if [[ $ARCH == aarch64 ]]; then 
echo 
echo -e "$red This Script Is Only For Arm User" 
else 
echo 
echo -e "$yellow Architecture Is $ARCH" 
fi 
sleep 1
clear 
echo 
echo -e "$red Starting Installation Process"
sleep 0.4 
cd $HOME 
echo -e "$blue Installing Requirements" 
apt update && apt upgrade -y && apt install clang axel wget -y 
echo -e "$red Downloading John The Ripper"
axel https://www.openwall.com/john/j/john-1.8.0.tar.xz 
echo -e "$green Extracting John The Ripper"
 tar -xf john-1.8.0.tar.xz 
echo -e "$blue Starting Install" 
cd $HOME/john-1.8.0/src/ 
make clean generic 
cp -rf $HOME/john-1.8.0/run $HOME/JohnTermux 
echo -e "$red Installation Is Finished" 
echo "To Run John Use This Commands" 
echo -e "$yellow Commands" 
echo ' cd $HOME/JohnTermux' 
echo ' ./john' 
echo -e "$red Remember This Is Not The Jumno/Community Edition"
echo "Please Subscribe My Channel"
rm -rf john-1.8.0.tar.xz john-1.8.0
